### ISSUE TITLE
Please publish to public npm registry

### ISSUE THREAD

**Issue by BlueRaja** [bsvensson/jaguarjs-jsdoc#1]
Your [esrijs](https://github.com/bsvensson/jaguarjs-jsdoc/tree/esrijs-sdk) branch is pretty much the best JSDoc template in existence.  Please publish it to npm to make it easy for others to find.

**Comment by BlueRaja** [comment]
Nevermind, I figured out how to do it myself: https://www.npmjs.com/package/jaguarjs-esri
If you give me your npm username I can add you as an admin

**Comment by BlueRaja** [comment]
Nevermind, apparently I was using `master`.  I can't actually get `esrijs` to work.

I forked your master, merged in a bunch of other PRs/patches from other repos, and published it as [`jaguarjs-jsdoc-patched`](https://www.npmjs.com/package/jaguarjs-jsdoc-patched)

**Comment by bsvensson** [comment]
Thanks @BlueRaja for your compliment. We aren't planning to continue any work on the esrijs branch but feel free to use it :)

We were using it as the start of our API Reference that is now deployed at https://developers.arcgis.com/javascript/beta/api-reference/
